--CREATE TABLE Hardware
--(
--    id INT IDENTITY PRIMARY KEY,
--    naziv        VARCHAR(50)    NOT NULL,
--    sifra        VARCHAR(50)   NOT NULL,
--    cijena       DECIMAL(10, 2) NOT NULL,
--    tip          VARCHAR(50) NOT NULL,
--    kolicina     INT NOT NULL
--);

CREATE TABLE IF NOT EXISTS Type  (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    naziv VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Hardware (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    naziv VARCHAR(50) NOT NULL,
    sifra VARCHAR(50) NOT NULL,
    cijena DECIMAL(10, 2) NOT NULL,
    tip_id INT NOT NULL,
    kolicina INT NOT NULL,
    FOREIGN KEY (tip_id) REFERENCES Type(id)
);